/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oracleofbacon;

/**
 *
 * @author Estudiante
 */
public class Acceso extends javax.swing.JFrame {

    /**
     * Creates new form Acseso
     */
    public Acceso() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn_Busquedad_por_pelicula = new javax.swing.JButton();
        Btn_Busquedad_por_separacion = new javax.swing.JButton();
        Btn_Busquedad_por_actor = new javax.swing.JButton();
        Btn_mas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Btn_salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/titulo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 420, 100));

        Btn_Busquedad_por_pelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton3.png"))); // NOI18N
        Btn_Busquedad_por_pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Busquedad_por_peliculaActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Busquedad_por_pelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 290, 50));

        Btn_Busquedad_por_separacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton1.png"))); // NOI18N
        Btn_Busquedad_por_separacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Busquedad_por_separacionActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Busquedad_por_separacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 440, 50));

        Btn_Busquedad_por_actor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton2.png"))); // NOI18N
        Btn_Busquedad_por_actor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Busquedad_por_actorActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Busquedad_por_actor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 340, 50));

        Btn_mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton4.png"))); // NOI18N
        jPanel1.add(Btn_mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 80, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kevin.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 80, 70));

        Btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        Btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/principal.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Busquedad_por_separacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Busquedad_por_separacionActionPerformed
        
        new Busqueda().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_Btn_Busquedad_por_separacionActionPerformed

    private void Btn_Busquedad_por_actorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Busquedad_por_actorActionPerformed
        
        new PeliculaInterfaz().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_Btn_Busquedad_por_actorActionPerformed

    private void Btn_Busquedad_por_peliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Busquedad_por_peliculaActionPerformed
        
        new Elenco().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_Btn_Busquedad_por_peliculaActionPerformed

    private void Btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_Btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Busquedad_por_actor;
    private javax.swing.JButton Btn_Busquedad_por_pelicula;
    private javax.swing.JButton Btn_Busquedad_por_separacion;
    private javax.swing.JButton Btn_mas;
    private javax.swing.JButton Btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
