/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oracleofbacon;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author fidel
 */
public class Main extends javax.swing.JFrame {

    Object[] oActors;
    File fMovies;
    Object[] oRelaciones;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();//prueba
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cargarActoresButton = new javax.swing.JButton();
        cargarPeliculasButton = new javax.swing.JButton();
        cargarRelacionButton = new javax.swing.JButton();
        procederButton = new javax.swing.JButton();
        actoresPath = new javax.swing.JTextField();
        peliculasPath = new javax.swing.JTextField();
        relacionPath = new javax.swing.JTextField();
        checkRelacion = new javax.swing.JLabel();
        checkActores = new javax.swing.JLabel();
        checkPeliculas = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargarActoresButton.setBackground(new java.awt.Color(79, 176, 129));
        cargarActoresButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cargarActoresButton.setText("Cargar actores");
        cargarActoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActoresButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cargarActoresButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 130, 30));

        cargarPeliculasButton.setBackground(new java.awt.Color(236, 159, 3));
        cargarPeliculasButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cargarPeliculasButton.setText("Cargar peliculas");
        cargarPeliculasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarPeliculasButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cargarPeliculasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 130, 30));

        cargarRelacionButton.setBackground(new java.awt.Color(65, 38, 11));
        cargarRelacionButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cargarRelacionButton.setText("Cargar relacion");
        cargarRelacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarRelacionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cargarRelacionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 130, 30));

        procederButton.setBackground(new java.awt.Color(45, 89, 116));
        procederButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        procederButton.setText("Proceder");
        procederButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procederButtonActionPerformed(evt);
            }
        });
        jPanel1.add(procederButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 170, 40));

        actoresPath.setEditable(false);
        actoresPath.setBackground(new java.awt.Color(79, 176, 129));
        actoresPath.setRequestFocusEnabled(false);
        jPanel1.add(actoresPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 420, 30));

        peliculasPath.setEditable(false);
        peliculasPath.setBackground(new java.awt.Color(236, 159, 3));
        peliculasPath.setRequestFocusEnabled(false);
        jPanel1.add(peliculasPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 420, 30));

        relacionPath.setEditable(false);
        relacionPath.setBackground(new java.awt.Color(65, 38, 11));
        relacionPath.setRequestFocusEnabled(false);
        jPanel1.add(relacionPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 420, 30));

        checkRelacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dry-clean.png"))); // NOI18N
        jPanel1.add(checkRelacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 50, 50));

        checkActores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dry-clean.png"))); // NOI18N
        jPanel1.add(checkActores, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 50, 50));

        checkPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dry-clean.png"))); // NOI18N
        jPanel1.add(checkPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 50, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/main.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -5, 800, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarRelacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarRelacionButtonActionPerformed
        // TODO add your handling code here:
        File fArchivoSeleccionado;
        JFileChooser seleccionarArchivo;
        seleccionarArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*CSV", "csv");
        seleccionarArchivo.setFileFilter(filtro);
        seleccionarArchivo.showOpenDialog(null);
        fArchivoSeleccionado = seleccionarArchivo.getSelectedFile();
        relacionPath.setText(fArchivoSeleccionado.getAbsolutePath());
        try {

            FileReader fr = new FileReader(fArchivoSeleccionado);
            BufferedReader br = new BufferedReader(fr);

           String cadena;
           this.oRelaciones = new Object[2];
           while((cadena = br.readLine())!= null)
           {
               String registro[] = cadena.split(",");
               this.oRelaciones[0] = registro[0];
               this.oRelaciones[1] = registro[1];
           }
            ImageIcon img = new ImageIcon("src/Imagenes/comprobado.png");
            checkRelacion.setIcon(img);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            ImageIcon img = new ImageIcon("src/Imagenes/boton-x.png");
            checkRelacion.setIcon(img);
        }
    }//GEN-LAST:event_cargarRelacionButtonActionPerformed

    private void cargarActoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActoresButtonActionPerformed
        // TODO add your handling code here:
        File fArchivoSeleccionado;
        JFileChooser seleccionarArchivo;
        seleccionarArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*CSV", "csv");
        seleccionarArchivo.setFileFilter(filtro);
        seleccionarArchivo.showOpenDialog(null);
        fArchivoSeleccionado = seleccionarArchivo.getSelectedFile();
        relacionPath.setText(fArchivoSeleccionado.getAbsolutePath());
       
        try {

            FileReader fr = new FileReader(fArchivoSeleccionado);
            BufferedReader br = new BufferedReader(fr);

            String cadena;
            this.oActors = new Object[3];
            while ((cadena = br.readLine()) != null) {
                String registro[] = cadena.split(",");
                this.oActors[0] = registro[0];
                this.oActors[1] = registro[1];
                this.oActors[2] = registro[2];
            }
            ImageIcon img = new ImageIcon("src/Imagenes/comprobado.png");
            checkRelacion.setIcon(img);
           
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            ImageIcon img = new ImageIcon("src/Imagenes/boton-x.png");
            checkRelacion.setIcon(img);
        }
    }//GEN-LAST:event_cargarActoresButtonActionPerformed

    private void cargarPeliculasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarPeliculasButtonActionPerformed
        // TODO add your handling code here:
        File archivoSeleccionado;
        JFileChooser seleccionarArchivo;
        seleccionarArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*CSV", "csv");
        seleccionarArchivo.setFileFilter(filtro);
        seleccionarArchivo.showOpenDialog(null);
        this.fMovies = seleccionarArchivo.getSelectedFile();
        peliculasPath.setText(this.fMovies.getAbsolutePath());
        try {

            FileReader fr = new FileReader(this.fMovies);
            BufferedReader br = new BufferedReader(fr);
           
//           String cadena;
//           Object[] elemento = new Object[3];
           
//           while((cadena = br.readLine())!= null)
//           {
//               String registro[] = cadena.split(",");
//               elemento[0] = registro[0];
//               elemento[1] = registro[1];
//               elemento[2] = registro[2];
//               System.out.println(elemento[1]);
//               
//           }
           
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_cargarPeliculasButtonActionPerformed

    private void procederButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procederButtonActionPerformed
        // TODO add your handling code here:
//        new Acceso().setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_procederButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actoresPath;
    private javax.swing.JButton cargarActoresButton;
    private javax.swing.JButton cargarPeliculasButton;
    private javax.swing.JButton cargarRelacionButton;
    private javax.swing.JLabel checkActores;
    private javax.swing.JLabel checkPeliculas;
    private javax.swing.JLabel checkRelacion;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField peliculasPath;
    private javax.swing.JButton procederButton;
    private javax.swing.JTextField relacionPath;
    // End of variables declaration//GEN-END:variables
}
